### ISSUE TITLE
Add missing character's slides 

### ISSUE THREAD

**Issue by rahulpanchal0106** [rahulpanchal0106/Animes#1]
Just down below of Nico Robin's, add three more slides to add remaining three crew members, which are [Brook](https://onepiece.fandom.com/wiki/Brookl), [Chopper](https://onepiece.fandom.com/wiki/Tony_Tony_Chopper), [Franky](https://onepiece.fandom.com/wiki/Franky).

**Comment by vedang999** [comment]
@rahulpanchal0106  could you assign this to me.
btw i'm on ep 1044

**Comment by vedang999** [comment]
@rahulpanchal0106 could you accept my PR

**Comment by rahulpanchal0106** [comment]
> @rahulpanchal0106 could you accept my PR

ya ya, I was busy with something,

sorry ;-;

**Comment by rahulpanchal0106** [comment]
Thanks for contributing :)
